// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7X_uyfU--EISI6RP-TlA0tmbb7r1ucqg',
    appId: '1:359611701677:web:a11e7fd3277f54b34ee924',
    messagingSenderId: '359611701677',
    projectId: 'crud1-flutter-cf38d',
    authDomain: 'crud1-flutter-cf38d.firebaseapp.com',
    storageBucket: 'crud1-flutter-cf38d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsLR9anwsoyKZreR2BXCSkn9zbFOouj3k',
    appId: '1:359611701677:android:917d424e73cd2ae34ee924',
    messagingSenderId: '359611701677',
    projectId: 'crud1-flutter-cf38d',
    storageBucket: 'crud1-flutter-cf38d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVUzMFpTnKB7a4jjPKvVxYe88yLLlF6mY',
    appId: '1:359611701677:ios:10c8227bb97a0b314ee924',
    messagingSenderId: '359611701677',
    projectId: 'crud1-flutter-cf38d',
    storageBucket: 'crud1-flutter-cf38d.appspot.com',
    iosBundleId: 'com.example.crud1Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVUzMFpTnKB7a4jjPKvVxYe88yLLlF6mY',
    appId: '1:359611701677:ios:10c8227bb97a0b314ee924',
    messagingSenderId: '359611701677',
    projectId: 'crud1-flutter-cf38d',
    storageBucket: 'crud1-flutter-cf38d.appspot.com',
    iosBundleId: 'com.example.crud1Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7X_uyfU--EISI6RP-TlA0tmbb7r1ucqg',
    appId: '1:359611701677:web:2756db7a83cd0f3f4ee924',
    messagingSenderId: '359611701677',
    projectId: 'crud1-flutter-cf38d',
    authDomain: 'crud1-flutter-cf38d.firebaseapp.com',
    storageBucket: 'crud1-flutter-cf38d.appspot.com',
  );
}
